name: Deploy to EC2

on:
  push:
    branches:
      - main2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/todo-api-deploy
            git pull origin main2
            npm install
            npm run build
            npm run prisma:deploy
            pm2 reload todo-app-test || pm2 start dist/main.js --name "todo-app-test"
            echo "Deployment successful!"
